# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 425ed285b32508227eb40a543c212ac82d79d85c1ca585aded8213c93c2f382f31ac15a4d615a4dfda601bb128a17e281ae150bf041f451b9fc69cec5023ba1d

test:
  secret_key_base: 0f34390ec8d7a0c338c477c1fc55b0bc35ec0bda0980cdf076d55b8bc2ea494b6df686677646aef12a29c9f5b013859004abd957b3dfa8c5e01749ec9fd5d4f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
